env: {}
terminationGracePeriodSeconds: 10
command:
  - bash
  - -c
  - |
    mkdir /app
    cd /app
    touch ready
    echo $HOSTNAME > index.html
    sleep $(( $RANDOM % 20 + 1 ))
    exec python3 -m http.server 8080

nameOverride: ""
fullnameOverride: "backend"
replicaCount: 3
image:
  repository: python
  tag: 3.11.6
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "150Mi"
    cpu: "50m"
  limits:
    memory: "150Mi"
    cpu: "200m"
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 1
  failureThreshold: 1
  successThreshold: 1
  httpGet:
    path: "/ready"
    port: http
livenessProbe: {}
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
nodeSelector: {}
tolerations: []
affinity: {}
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
